config/routes.rb
Rails.application.routes.draw do

  
  root 'scripts#index'

  resources :scripts do
    resources :scenes do
      resources :clips
    end
    resources :comments
  end
    

  get "scenes/:id" => "scenes#show", as: :scene

end

app/models/clip.rb
class Clip < ActiveRecord::Base
	belongs_to :scene
	has_attached_file :video,
                    :path => ":rails_root/public/videos/:class/:attachement/:id/:basename_:style.:extension",
    				:url => "/videos/:class/:attachement/:id/:basename_:style.:extension"

    validates_attachment :video, :presence => true, :content_type => { :content_type => ["video/mp4"] }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :script
end

app/models/scene.rb
class Scene < ActiveRecord::Base
	belongs_to :script
	has_many :clips
end

app/models/script.rb
class Script < ActiveRecord::Base
	has_many :scenes
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
	def new
		@script = params[:script_id]
		@scene = params[:scene_id]
		@clip = Clip.new
	end

	def create
		@script = Script.find(params[:script_id])
		@scene = @script.scenes.find(params[:scene_id])
		if @clip = @scene.clips.create(clip_params)
			vids = @scene.numOfVids
			vids = vids + 1
			@scene.numOfVids = vids
			@scene.save
			render :text => '<script type="text/javascript"> window.close(); </script>'
		else
			render 'new'
		end
	end

	def update
		@script = Script.find(params[:script_id])
		@scene = @script.scenes.find(params[:scene_id])
		@clip = @scene.clips.find(params[:id])
		@clip.increment(:votecount)
		redirect_to :back
	end
	
	private
		def clip_params
			params.require(:clip).permit(:video)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
    @script = Script.find(params[:script_id])
    @comment = @script.comments.create(comment_params)
    redirect_to script_path(@script)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
	def show
		@scene = Scene.find(params[:id])
		@script = @scene.script
	end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
	def index
		@homepage = true
		@scriptList = Script.all
	end

	def show
		@script = Script.find(params[:id])
		@scenes = @script.scenes
		@vids = []
		@scenes.each do |scene|
			@clips = scene.clips
			if !(@clips.empty?) then
				@vids.push @clips.order("created_at DESC").first
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/clips/new.html.erb
<h2>Upload Video</h2>
</br>
<div id="chooseFile" style="padding-left:30%;">
	<%= form_for [:script, :scene, @clip] do |f| %>
		<%= f.label :video_link %>
		<%= f.file_field :video %>
		<br><br>
		<%= f.submit "Submit", :class=>"btn btn-primary" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki Studio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @homepage ? 'landing' : ''%>">
<%= yield %>
</body>
</html>

app/views/scenes/show.html.erb
<h2><%= @script.scriptname %> - Scene <%= @scene.sceneNumber %></h2>
<div class="action-button">
	<button type="button" class="btn btn-default btn-sm" style="margin-right:2%;">Print Script</button>
	<%= link_to "Upload Video", new_script_scene_clip_path(@script,@scene), class: "btn btn-default btn-sm" %>
</div>
<br>
<br>
<h4>Setting Guidelines</h4>
<p><%= @scene.settingGuideline %></p>
<h4>Character Guidelines</h4>
<p><%= @scene.characterGuideline %></p>
<br><br>
<p><%= simple_format(@scene.sceneText) %></p>

app/views/scripts/index.html.erb
<div class="top">
    <h1>Wiki Studio</h1>
</div>

<p style="text-align:center;color:white;font-size:1.5em;">Wiki Studio is a collaborative video platform where everyone can be part of a fun project</p>
<div class="container" id="existing">
    <h2 class="section-heading">Click the script below to start</h2>
    <% @scriptList.each do |s| %>
        <% if s.genre == "drama"%>
            <p><%= link_to s.scriptname, script_path(s), class: "script-name" %></p>
        <% end %>
    <% end %>        
</div>

app/views/scripts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Upload New Script</title>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    	<div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#">Wiki Studios</a>
        </div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        	<ul class="nav navbar-nav navbar-right">
            	<li>
                	<a id="modal_trigger" href="#modal" class="btn">Register / Log In</a>
            	</li>
        	</ul>
    	</div>
	</nav>
	
	<h1>Upload A New Script</h1>
	<div class="container">
		<%= form_for @script do |f| %>
			<%= f.label :title %>:
			<%= f.text_field :scriptname %>
			<br><br>
			<%= f.label :author %>:
			<%= f.text_field :authorid %>
			<br><br>
			<%= f.label :genre %>:
			<%= f.text_field :genre %>	
			<br><br>
			<%= f.label :summary %>:
			<%= f.text_area :summary %>	
			<br><br>
			<%= f.label :production_notes %>:
			<%= f.text_area :notes %>
			<br><br>
			<%= f.submit %>
		<% end %>
	</div>
</body>	
</html>

app/views/scripts/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            <h4><%= link_to "Wiki Studio",  controller: "scripts", action: "index", class: "navbar-brand topnav" %></h4>

        </div>
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div>
</nav>

<br></br>
<br></br>
<div class="videoDiv">
  <% if @vids.empty? %>
    <h2 style="margin-left: 35px; color: white;"><%= @script.scriptname %></h2>
    <div id="video_container">
      <%= video_tag [], :size => "480x480", :controls => true, :autobuffer => true, :poster => 'screenshot.png' %>
    </div>         
  <% else %>
    <div>
      <h2 style="margin-left: 35px; color: white; display: inline-block"><%= @script.scriptname %></h2>
      <p style="float: right; color: white; margin-right:2%; margin-top:2%; font-size: 25px;">Playlist<p>
    </div>  
    <figure id="video_player">
      <div id="video_container">
        <%= video_tag [@vids.first.video.url], :controls => true, :autobuffer => true %>
      </div>
      <figcaption>
        <% @vids.each do |vid| %>
          <%= link_to image_tag("scene"+vid.scene.sceneNumber.to_s+".png"), vid.video.url %>
        <% end %>
      </figcaption>
    </figure>
  <% end %>
  <br></br>
  <div class="scene-buttons-container">
    <% @scenes.each do |s| %>
      <% if s.numOfVids == 0 %>
        <%= link_to "Scene "+s.sceneNumber.to_s, script_scene_path(@script, s), class: "scene_buttons_white",
      :onclick=>"window.open(this.href,'popUpWindow', 'height=600,width=600,left=300,top=100,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes');return false;" %>
      <% else %>
        <%= link_to "Scene "+s.sceneNumber.to_s, script_scene_path(@script, s), class: "scene_buttons_blue_dark",
      :onclick=>"window.open(this.href,'popUpWindow', 'height=600,width=600,left=300,top=100,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes');return false;" %>
      <% end %>
    <% end %>
  </div>
</center>
</div>

<div class="box"><h3>Plot</h3>
  <p><%= @script.summary%></p>
</div>
<br>
<div class="box"><h3>Production Notes</h3>
  <p><%= @script.notes%></p>
</div>
<br></br>

<br></br>
<br></br>

<!--DIV for comments-->
<div id="commentbox">
<h2 style="color:white;">Comments</h2>
<% @script.comments.each do |comment| %>
    <div id="comment">
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
        </div>
<% end %>
            </div>
 
<div style="margin-left:2%;">
<h3>Add a comment:</h3>
<%= form_for([@script, @script.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 </div>

<!--Code for video playlist. Adapted from http://demosthenes.info/blog/792/Create-A-Simple-HTML5-Video-Playlist-->
<script type="text/javascript">
  
  var video_player = document.getElementById("video_player");
  var video = video_player.getElementsByTagName("video")[0];
  var video_links = video_player.getElementsByTagName("figcaption")[0];
  var currentVid = 0;
  var link_list = [];
  var allLnks = video_links.children;
  var lnkNum = allLnks.length;
  video_links.children[0].classList.add("currentvid");

  function playVid(index) {
      video_links.children[index].classList.add("currentvid");
      video.src = link_list[index];
      currentVid = index;
      video.load();
      video.play();
  }
  
  for (var i=0; i<lnkNum; i++) {
    link_list[i] = allLnks[i].href;
    (function(index){
      allLnks[i].onclick = function(i){
        i.preventDefault();
        for (var i=0; i<lnkNum; i++) {
          allLnks[i].classList.remove("currentvid");
        }     
        playVid(index);
      }
    })(i);
  }

  video.addEventListener('ended', function () {
    allLnks[currentVid].classList.remove("currentvid");
    if ((currentVid + 1) >= lnkNum) { nextVid = 0 } else { nextVid = currentVid+1 }
      playVid(nextVid);
  });
</script>